name: 'domelement'
version: 0.0.1
description: A wrapper class for Element.
author: Gonzalo Chumillas <gchumillas@email.com>
homepage: https://github.com/soloproyectos-dart/domelement
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: '>=1.0.1 <2.0.0'
  quiver: '>=0.22.0 < 1.0.0'
transformers:
- dart_to_js_script_rewriter
