name: 'domelement'
version: 1.0.0
description: A client-side library to traverse and manipulate DOM documents.
author: Gonzalo Chumillas <gchumillas@email.com>
homepage: https://github.com/soloproyectos-dart/domelement
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: '>=1.0.1 <2.0.0'
transformers:
- dart_to_js_script_rewriter
